// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TexAuto.Data;

#nullable disable

namespace TexAuto.Migrations
{
    [DbContext(typeof(TexAutoContext))]
    [Migration("20250427094812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TexAuto.Models.Domain.Entries.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime4")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime4")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalShifts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Shift");
                });
#pragma warning restore 612, 618
        }
    }
}
